project_id = "atwnmovdnblcqyvhaxls"

[storage]
file_size_limit = "250MB"

[functions.process-email-queue]
verify_jwt = true

[functions.gmail-oauth-callback]
verify_jwt = false

[functions.send-gmail-email]
verify_jwt = false